#pragma once

#include "../SDK.h"

// Name: Freddys, Version: 1.0.0

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

namespace SDK
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_C09525B0437353161A9AEFB127074E62
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_C09525B0437353161A9AEFB127074E62_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_C3B0C2C74F31BED44DA71BB323B87333
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_C3B0C2C74F31BED44DA71BB323B87333_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_977F98C446309124A2EA1F9ABCF4DD54
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_977F98C446309124A2EA1F9ABCF4DD54_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_90B6D0F94DBB4B63EEBD6DB9DE4BAE05
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_90B6D0F94DBB4B63EEBD6DB9DE4BAE05_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_103318BD46D6F6B35955A89177E7AC84
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_103318BD46D6F6B35955A89177E7AC84_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_B2F83E9440D6E8FD51566693B6B59759
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_B2F83E9440D6E8FD51566693B6B59759_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_75542EDE4CFBC45D81EE66834B3E2E8B
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_75542EDE4CFBC45D81EE66834B3E2E8B_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_72F7686A4B9F4EE7F68647A95E4200AA
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_72F7686A4B9F4EE7F68647A95E4200AA_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_37DE24A8411A10117240139A158397E1
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_37DE24A8411A10117240139A158397E1_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_84247AB7427EC743B1F0E08AF8B4A1DB
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_84247AB7427EC743B1F0E08AF8B4A1DB_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_B11B38674C57A66BC4B663ABD90C5582
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_B11B38674C57A66BC4B663ABD90C5582_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_BB83FB554A353B557575019113A742E5
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_BB83FB554A353B557575019113A742E5_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_D936853D45211C94E0D0D7925C7A63A6
struct UOffice02_Withered_Chica_AnimBp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_AnimGraphNode_TransitionResult_D936853D45211C94E0D0D7925C7A63A6_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.BlueprintBeginPlay
struct UOffice02_Withered_Chica_AnimBp_C_BlueprintBeginPlay_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.AnimNotify_CheckForMask
struct UOffice02_Withered_Chica_AnimBp_C_AnimNotify_CheckForMask_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.AnimNotify_CallFlickerLight
struct UOffice02_Withered_Chica_AnimBp_C_AnimNotify_CallFlickerLight_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.AnimNotify_FlickerCamera
struct UOffice02_Withered_Chica_AnimBp_C_AnimNotify_FlickerCamera_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.AnimNotify_RevealActor
struct UOffice02_Withered_Chica_AnimBp_C_AnimNotify_RevealActor_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.AnimNotify_HideActor
struct UOffice02_Withered_Chica_AnimBp_C_AnimNotify_HideActor_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.AnimNotify_WitheredAttack
struct UOffice02_Withered_Chica_AnimBp_C_AnimNotify_WitheredAttack_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.AnimNotify_WitheredRetreat
struct UOffice02_Withered_Chica_AnimBp_C_AnimNotify_WitheredRetreat_Params
{
};

// Function Office02_Withered_Chica_AnimBp.Office02_Withered_Chica_AnimBp_C.ExecuteUbergraph_Office02_Withered_Chica_AnimBp
struct UOffice02_Withered_Chica_AnimBp_C_ExecuteUbergraph_Office02_Withered_Chica_AnimBp_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
